# Generated by Django 6.0.5 on 2026-05-20 18:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceTrajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('femmesUniquement', models.BooleanField(default=False, verbose_name='Femmes uniquement')),
                ('nonFumeur', models.BooleanField(default=False, verbose_name='Non-fumeur')),
                ('accepteAnimaux', models.BooleanField(default=False, verbose_name='Accepte les animaux')),
                ('accepteBagagesVolumineux', models.BooleanField(default=False, verbose_name='Accepte les bagages volumineux')),
                ('musiqueAutorisee', models.BooleanField(default=False, verbose_name='Musique autorisée')),
                ('pauseCafe', models.BooleanField(default=False, verbose_name='Pause café')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('photoProfil', models.ImageField(blank=True, default='profiles/default.png', null=True, upload_to='profiles/', verbose_name='Photo de profil')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('DESACTIVE', 'Désactivé'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=20, verbose_name='Statut du compte')),
                ('numeroPermis', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de permis')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('dateEnvoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['dateEnvoi'],
            },
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('villeDepart', models.CharField(max_length=100, verbose_name='Ville de départ')),
                ('villeArrivee', models.CharField(max_length=100, verbose_name="Ville d'arrivée")),
                ('dateTrajet', models.DateField(verbose_name='Date du trajet')),
                ('heureDepart', models.TimeField(verbose_name='Heure de départ')),
                ('prixParPlace', models.DecimalField(decimal_places=2, max_digits=10, max_length=10, verbose_name='Prix par place (TND)')),
                ('placesDisponibles', models.IntegerField(verbose_name='Places initiales disponibles')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('COMPLET', 'Complet'), ('ANNULE', 'Annulé'), ('TERMINE', 'Terminé')], default='OUVERT', max_length=20, verbose_name='Statut')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides_driven', to=settings.AUTH_USER_MODEL, verbose_name='Conducteur')),
                ('preferences', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ride', to='core.preferencetrajet', verbose_name='Préférences')),
            ],
            options={
                'verbose_name': 'Trajet',
                'verbose_name_plural': 'Trajets',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateReservation', models.DateTimeField(auto_now_add=True, verbose_name='Date de réservation')),
                ('nombrePlacesReservees', models.IntegerField(verbose_name='Places réservées')),
                ('prixTotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix total (TND)')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRMEE', 'Confirmée'), ('REFUSEE', 'Refusée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('note', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Note (1-5)')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire / Avis')),
                ('dateAvis', models.DateTimeField(blank=True, null=True, verbose_name="Date de l'avis")),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Passager')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.trajet', verbose_name='Trajet')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=50, verbose_name='Marque')),
                ('modele', models.CharField(max_length=50, verbose_name='Modèle')),
                ('couleur', models.CharField(max_length=30, verbose_name='Couleur')),
                ('immatriculation', models.CharField(max_length=50, verbose_name='Immatriculation')),
                ('typeVehicule', models.CharField(max_length=50, verbose_name='Type de Véhicule')),
                ('nombrePlaces', models.IntegerField(verbose_name='Nombre de places')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
            },
        ),
        migrations.AddField(
            model_name='trajet',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='core.vehicule', verbose_name='Véhicule'),
        ),
    ]
